# Generated by Django 3.2.5 on 2021-10-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('10', 'jterm'), ('20', 'spring'), ('30', 'summer'), ('40', 'fall')], default='04', max_length=2),
            preserve_default=False,
        ),
    ]
